### ISSUE TITLE
Some questions about submitting job 

### ISSUE THREAD

**Issue by gxfun** [Microsoft/pai#402]
Hi
When I upload the json of job, it reports the problem:
  `internal server error`

[the json of our job](https://github.com/gxfun/Dockerfile/blob/master/configuration/job_json.json)

Thanks

**Comment by abuccts** [comment]
You should also delete `// ...` comment lines in json file since comment is not supported in json.
But I don't think it will cause 500 error.

**Comment by gxfun** [comment]
@abuccts 
Thanks!
I have already deleted `// ...` before submitting job

[the log of  executing command `kubectl logs REST_SERVER_POD_NAME`](https://github.com/gxfun/Dockerfile/blob/master/configuration/detials_of_test_log.yaml)

Besides, I don't understand what you mean about `the commit hash of pai code`. 
I am a beginner and hope to get your help。

**Comment by gxfun** [comment]
@abuccts

I downloaded the code of PAI about a weeks ago by `git clone`. Then I copy the code to our service machine since it can't access the internet.

Do I need build images again  if I `git clone` the latest verdion？

**Comment by gxfun** [comment]
@abuccts 
Hi, I submit the job by webportal.

**Comment by abuccts** [comment]
Hi, there's an issue with rest server at that time and it's fixed in #383. You can
- `git pull` to update the code and build the rest server image only
- `git checkout v0.3.0-alpha` or download the [release version](https://github.com/Microsoft/pai/releases/tag/v0.3.0-alpha) and deploy again

The release version will be more stable than the latest version.

Hope it helps!

**Comment by gxfun** [comment]
@abuccts

After  I change the job name to a string without `-`, this still report  `internal server error` and  no other error in [the  log of  `kubectl logs REST_POD_NAME`](https://github.com/gxfun/Dockerfile/tree/master), but still can't find job in `job view`.

I will try to do according to your suggestion.

Thanks!

**Comment by fanyangCS** [comment]
close this issue as no further info.
